<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $skills = [
            ['name' => 'Web Development'],
            ['name' => 'Graphic Design'],
            ['name' => 'Content Writing'],
            ['name' => 'Social Media Marketing'],
            ['name' => 'Search Engine Optimization (SEO)'],
            ['name' => 'Data Entry'],
            ['name' => 'Copywriting'],
            ['name' => 'Translation'],
            ['name' => 'Video Editing'],
            ['name' => 'App Development'],
            ['name' => 'Copywriting'],
            ['name' => 'Virtual Assistant'],
            ['name' => 'Customer Service'],
            ['name' => 'Product Listing'],
            ['name' => 'E-commerce'],
            ['name' => 'Data Analysis'],
            ['name' => 'Web scraping'],
            ['name' => 'Copyediting'],
            ['name' => 'Proofreading'],
            ['name' => 'Bookkeeping'],
            ['name' => 'Accounting'],
            ['name' => 'Tax Preparation'],
            ['name' => 'Payroll'],
            ['name' => 'Invoicing'],
            ['name' => 'QuickBooks'],
            ['name' => 'Xero'],
            ['name' => 'FreshBooks'],
            ['name' => 'Wave'],
            ['name' => 'Zoho Books'],
            ['name' => 'Tally'],
            ['name' => 'Sage'],
            ['name' => 'Microsoft Excel'],
            ['name' => 'Google Sheets'],
            ['name' => 'Microsoft Word'],
            ['name' => 'Google Docs'],
            ['name' => 'PowerPoint'],
            ['name' => 'Keynote'],
            ['name' => 'Prezi'],
            ['name' => 'Canva'],
            ['name' => 'Adobe Photoshop'],
            ['name' => 'Adobe Illustrator'],
            ['name' => 'Adobe InDesign'],
            ['name' => 'Adobe XD'],
            ['name' => 'Adobe Premiere Pro'],
            ['name' => 'Final Cut Pro'],
            ['name' => 'iMovie'],
            ['name' => 'Audacity'],
            ['name' => 'GarageBand'],
            ['name' => 'Logo Design'],
            ['name' => 'Brand Identity'],
            ['name' => 'Illustration'],
            ['name' => 'Character Design'],
            ['name' => '3D Modelling'],
            ['name' => '3D Animation'],
            ['name' => 'Motion Graphics'],
            ['name' => 'Augmented Reality (AR)'],
            ['name' => 'Virtual Reality (VR)'],
            ['name' => 'Unity'],
            ['name' => 'Unreal Engine'],
            ['name' => 'Blender'],
            ['name' => 'Maya'],
            ['name' => 'Cinema 4D'],
            ['name' => 'Houdini'],
            ['name' => 'After Effects'],
            ['name' => 'JavaScript'],
            ['name' => 'React'],
            ['name' => 'Vue'],
            ['name' => 'Angular'],
            ['name' => 'Node'],
            ['name' => 'Express'],
            ['name' => 'MongoDB'],
            ['name' => 'MySQL'],
            ['name' => 'PostgreSQL'],
            ['name' => 'SQLite'],
            ['name' => 'Oracle'],
            ['name' => 'SQL Server'],
            ['name' => 'Firebase'],
            ['name' => 'AWS'],
            ['name' => 'Azure'],
            ['name' => 'Google Cloud'],
            ['name' => 'Heroku'],
            ['name' => 'DigitalOcean'],
            ['name' => 'Linode'],
            ['name' => 'Vultr'],
            ['name' => 'Docker'],
            ['name' => 'Kubernetes'],
            ['name' => 'Terraform'],
            ['name' => 'Ansible'],
            ['name' => 'Puppet'],
            ['name' => 'Chef'],
            ['name' => 'SaltStack'],
            ['name' => 'Jenkins'],
            ['name' => 'Travis CI'],
            ['name' => 'CircleCI'],
            ['name' => 'GitHub Actions'],
            ['name' => 'Bitbucket Pipelines'],
            ['name' => 'AWS CodePipeline'],
            ['name' => 'Azure Pipelines'],
            ['name' => 'Google Cloud Build'],
            ['name' => 'Chatbot Development'],
            ['name' => 'IoT Development'],
            ['name' => 'Blockchain Development'],
            ['name' => 'Smart Contract Development'],
            ['name' => 'Cryptocurrency Development'],
            ['name' => 'Machine Learning'],
            ['name' => 'Deep Learning'],
            ['name' => 'Natural Language Processing (NLP)'],
            ['name' => 'Computer Vision'],
            ['name' => 'Robotics'],
            ['name' => 'Quantum Computing'],
        ];

        $languages = [
            ['name' => 'JavaScript'],
            ['name' => 'Python'],
            ['name' => 'Java'],
            ['name' => 'C++'],
            ['name' => 'C#'],
            ['name' => 'PHP'],
            ['name' => 'Ruby'],
            ['name' => 'Swift'],
            ['name' => 'TypeScript'],
            ['name' => 'Rust'],
            ['name' => 'Go'],
            ['name' => 'Kotlin'],
            ['name' => 'C'],
            ['name' => 'Scala'],
            ['name' => 'Dart'],
            ['name' => 'R'],
            ['name' => 'Objective-C'],
            ['name' => 'SQL'],
            ['name' => 'Perl'],
            ['name' => 'Haskell'],
            ['name' => 'Rust'],
        ];

        Skill::insert($skills);
        Skill::insert($languages);
    }
}
